id: CuckooTest
version: -1
name: CuckooTest
description: '-'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a4497e56-ff45-468f-848c-c998df7499bf
    type: start
    task:
      id: a4497e56-ff45-468f-848c-c998df7499bf
      version: -1
      name: ""
      description: '-'
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 5e44c33f-e4c4-44e9-8f29-8eab9df78523
    type: regular
    task:
      id: 5e44c33f-e4c4-44e9-8f29-8eab9df78523
      version: -1
      name: Get file
      description: getting file using get
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile: {}
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/pdf_noeof.pdf
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 5c09350e-46d2-4f1c-8089-c0a5d30d3948
    type: regular
    task:
      id: 5c09350e-46d2-4f1c-8089-c0a5d30d3948
      version: -1
      name: Delete Context
      description: delete context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 50f69c9e-415e-4864-8ffd-9c0fc46c782d
    type: playbook
    task:
      id: 50f69c9e-415e-4864-8ffd-9c0fc46c782d
      version: -1
      name: Detonate File - Cuckoo
      description: Detonating file with Cuckoo
      playbookName: Detonate File - Cuckoo
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      File:
        simple: ${File}
      interval:
        simple: "1"
      timeout:
        simple: "10"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 2a48194c-5acc-4e9f-83e9-a29ea013813b
    type: title
    task:
      id: 2a48194c-5acc-4e9f-83e9-a29ea013813b
      version: -1
      name: Done
      description: done file
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2875
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 9678d053-64fe-490d-8fbf-7ee94f989379
    type: playbook
    task:
      id: 9678d053-64fe-490d-8fbf-7ee94f989379
      version: -1
      name: Detonate URL - Cuckoo
      description: url detonation playbook
      playbookName: Detonate URL - Cuckoo
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      URL:
        simple: google.com
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 1a86175a-4af8-4237-814c-c360da3f1398
    type: title
    task:
      id: 1a86175a-4af8-4237-814c-c360da3f1398
      version: -1
      name: FileDetonate Done
      description: done file detonate
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 3dce6be2-3519-4ba4-8911-2254ce34e9f1
    type: regular
    task:
      id: 3dce6be2-3519-4ba4-8911-2254ce34e9f1
      version: -1
      name: Delete Context
      description: delete context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2525
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: ecc0ee61-3409-49bf-8a00-3a656165b5ae
    type: regular
    task:
      id: ecc0ee61-3409-49bf-8a00-3a656165b5ae
      version: -1
      name: Get file
      description: getting file using get
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/pdf-example-password.pdf
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 2f15ba03-bbac-461e-89b0-5f2640b4f862
    type: regular
    task:
      id: 2f15ba03-bbac-461e-89b0-5f2640b4f862
      version: -1
      name: cuckoo-get-task-report
      description: Retrieve report
      script: Cuckoo Sandbox|||cuckoo-get-task-report
      type: regular
      iscommand: true
      brand: Cuckoo Sandbox
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      id:
        complex:
          root: Cuckoo.Task
          accessor: ID
          transformers:
          - operator: FirstArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 144798e8-da29-40d0-8f83-98b64b1c1df3
    type: condition
    task:
      id: 144798e8-da29-40d0-8f83-98b64b1c1df3
      version: -1
      name: Check if file's data is in output
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Cuckoo.Task.FileInfo.sha1
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 76d18460-d558-4a55-8319-1ad6d974737d
    type: title
    task:
      id: 76d18460-d558-4a55-8319-1ad6d974737d
      version: -1
      name: File data output check done
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 2ab819ba-29c5-416e-86d0-9eb38629ffe2
    type: title
    task:
      id: 2ab819ba-29c5-416e-86d0-9eb38629ffe2
      version: -1
      name: Second file detonation
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 2e89665d-0958-4d8c-8ce4-6b849ca920aa
    type: regular
    task:
      id: 2e89665d-0958-4d8c-8ce4-6b849ca920aa
      version: -1
      name: Delete Context
      description: delete context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: c01890db-b209-44b7-8218-19e4b7110cdd
    type: regular
    task:
      id: c01890db-b209-44b7-8218-19e4b7110cdd
      version: -1
      name: cuckoo-get-task-report
      description: Retrieve report
      script: Cuckoo Sandbox|||cuckoo-get-task-report
      type: regular
      iscommand: true
      brand: Cuckoo Sandbox
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      id:
        complex:
          root: Cuckoo.Task
          accessor: ID
          transformers:
          - operator: FirstArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2030
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: 59c4efad-56e9-480d-89a7-a53cd0fe1948
    type: condition
    task:
      id: 59c4efad-56e9-480d-89a7-a53cd0fe1948
      version: -1
      name: Check if file's data is in output
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Cuckoo.Task.FileInfo.sha1
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2205
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: db63dc4a-0052-49ac-8ee6-7e923711eb00
    type: playbook
    task:
      id: db63dc4a-0052-49ac-8ee6-7e923711eb00
      version: -1
      name: Detonate File - Cuckoo
      description: Detonating file with Cuckoo
      playbookName: Detonate File - Cuckoo
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      File:
        simple: ${File}
      interval:
        simple: "1"
      timeout:
        simple: "10"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: 350f6732-b5ec-40a0-89db-d38af1e5bc7e
    type: title
    task:
      id: 350f6732-b5ec-40a0-89db-d38af1e5bc7e
      version: -1
      name: FileDetonate Done
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1885
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2890,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
